version: "3.8"

services:
  sish:
    image: antoniomika/sish:v1.1.7

    command: "\
              --config /config/config.yml \
              --authentication-password=${SSH_PASS} \
              --domain=${DOMAIN} \
              --bind-hosts=${DOMAIN} \
             "

    restart: unless-stopped

    networks:
      proxy-net: {}

    volumes:
      - ./config/sish/config.yml:/config/config.yml
      - ./data/sish/pubkeys:/pubkeys
      - ./data/sish/keys:/keys

    labels:
      - "traefik.enable=true"
      - "traefik.http.services.sish.loadbalancer.server.port=80"
      - "traefik.http.routers.sish.service=sish"
      - "traefik.http.routers.sish.entrypoints=websecure"
      - "traefik.http.routers.sish.rule=HostRegexp(`{subdomain:([^.]+\\.)}${DOMAIN}`)"
      - "traefik.http.routers.sish.tls.certresolver=letsencrypt-dns"
      - "traefik.http.routers.sish.tls.domains[0].main=*.${DOMAIN}"

      - "traefik.tcp.services.sish-ssh.loadbalancer.server.port=22"
      - "traefik.tcp.routers.sish-ssh.service=sish-ssh"
      - "traefik.tcp.routers.sish-ssh.entrypoints=ssh"
      - "traefik.tcp.routers.sish-ssh.rule=HostSNI(`*`)"

  web:
    image: dannyben/madness:0.9.4

    volumes:
      - ./README.md:/docs/README.md

    restart: unless-stopped

    ports:
      - 3000:3000

    networks:
      - proxy-net

    labels:
      - "traefik.enable=true"
      - "traefik.http.services.tunnel-web.loadbalancer.server.port=3000"
      - "traefik.http.routers.tunnel-web.service=tunnel-web"
      - "traefik.http.routers.tunnel-web.entrypoints=websecure"
      - "traefik.http.routers.tunnel-web.rule=Host(`${DOMAIN}`)"

networks:
  proxy-net:
    external: true
