ssh-address: :22
http-address: :80
https: true

authentication: true
authentication-keys-directory: /pubkeys
private-key-directory: /keys/ssh_key

bind-random-ports: false
bind-random-subdomains: false
bind-random-subdomains-length: 4

service-console: false
